'use client';

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Download, Loader2 } from 'lucide-react';
import { InterviewReport } from '@/lib/types';
import { getScoreLabel, formatDate } from '@/lib/utils';

interface ReportExportProps {
  report: InterviewReport;
}

export function ReportExport({ report }: ReportExportProps) {
  const [isExporting, setIsExporting] = useState(false);

  const exportToPDF = async () => {
    setIsExporting(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF({ orientation: 'portrait', format: 'a4' });

      const margin = 20;
      let y = margin;
      const lineH = 7;
      const pageW = doc.internal.pageSize.getWidth();
      const maxW = pageW - margin * 2;

      const addText = (text: string, size = 10, bold = false, color = [0, 0, 0]) => {
        doc.setFontSize(size);
        doc.setFont('helvetica', bold ? 'bold' : 'normal');
        doc.setTextColor(...(color as [number, number, number]));
        const lines = doc.splitTextToSize(text, maxW);
        if (y + lines.length * lineH > doc.internal.pageSize.getHeight() - margin) {
          doc.addPage();
          y = margin;
        }
        doc.text(lines, margin, y);
        y += lines.length * lineH + 2;
      };

      const addSeparator = () => {
        doc.setDrawColor(200, 200, 200);
        doc.line(margin, y, pageW - margin, y);
        y += 6;
      };

      // Title
      addText('INTERVIEWAI - INTERVIEW REPORT', 20, true, [109, 40, 217]);
      addText(formatDate(report.completedAt), 10, false, [120, 120, 120]);
      y += 4;
      addSeparator();

      // Candidate Info
      addText('CANDIDATE INFORMATION', 13, true, [50, 50, 50]);
      addText(`Name: ${report.candidateName}`);
      addText(`Role: ${report.jobRole}`);
      addText(`Difficulty: ${report.difficulty.charAt(0).toUpperCase() + report.difficulty.slice(1)}`);
      addText(`Interview Type: ${report.interviewType}`);
      y += 4;

      // Scores
      addSeparator();
      addText('PERFORMANCE SCORES', 13, true, [50, 50, 50]);
      addText(`Overall Score: ${report.overallScore}/100 (${getScoreLabel(report.overallScore)})`, 12, true, [109, 40, 217]);
      addText(`Technical Knowledge: ${report.scoreBreakdown.technicalKnowledge}/100`);
      addText(`Communication: ${report.scoreBreakdown.communication}/100`);
      addText(`Relevance: ${report.scoreBreakdown.relevance}/100`);
      addText(`Confidence: ${report.scoreBreakdown.confidence}/100`);
      y += 4;

      // Strengths
      addSeparator();
      addText('STRENGTHS', 13, true, [50, 50, 50]);
      report.strengths.forEach(s => addText(`• ${s}`));
      y += 4;

      // Weaknesses
      addSeparator();
      addText('AREAS FOR IMPROVEMENT', 13, true, [50, 50, 50]);
      report.weaknesses.forEach(w => addText(`• ${w}`));
      y += 4;

      // Skill Gaps
      addSeparator();
      addText('SKILL GAPS', 13, true, [50, 50, 50]);
      report.skillGaps.forEach(g => addText(`• ${g}`));
      y += 4;

      // Recommendations
      addSeparator();
      addText('RECOMMENDATIONS', 13, true, [50, 50, 50]);
      report.recommendations.forEach((r, i) => addText(`${i + 1}. ${r}`));
      y += 4;

      // Learning Roadmap
      addSeparator();
      addText('30-DAY LEARNING ROADMAP', 13, true, [50, 50, 50]);
      report.learningRoadmap.forEach(week => {
        addText(`Week ${week.week}: ${week.title}`, 11, true);
        addText(`Goal: ${week.goal}`, 9, false, [80, 80, 80]);
        week.topics.forEach(t => addText(`  • ${t}`, 9));
        y += 2;
      });

      // Footer
      addSeparator();
      addText('Generated by InterviewAI - Powered by Google Gemini', 9, false, [150, 150, 150]);

      doc.save(`interview-report-${report.candidateName.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);
    } catch (err) {
      console.error('Export failed:', err);
      alert('Export failed. Please try again.');
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button
      onClick={exportToPDF}
      disabled={isExporting}
      className="gap-2 bg-gradient-to-r from-violet-600 to-indigo-600 text-white border-0 hover:from-violet-700 hover:to-indigo-700"
    >
      {isExporting ? (
        <>
          <Loader2 className="w-4 h-4 animate-spin" />
          Exporting...
        </>
      ) : (
        <>
          <Download className="w-4 h-4" />
          Export PDF
        </>
      )}
    </Button>
  );
}
