'use client';

import { motion } from 'framer-motion';
import {
  Brain, BarChart3, FileText, Trophy, Zap, BookOpen
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Questions',
    description: 'Dynamic questions generated by Groq AI, tailored to your specific role, experience level, and interview type.',
    iconColor: 'text-violet-600 dark:text-violet-400',
    bg: 'bg-violet-500/10 dark:bg-violet-500/15',
    border: 'hover:border-violet-500/40',
    featured: true,
  },
  {
    icon: BarChart3,
    title: 'Real-Time Scoring',
    description: 'Instant evaluation across 4 dimensions: technical knowledge, communication, relevance, and confidence.',
    iconColor: 'text-blue-600 dark:text-blue-400',
    bg: 'bg-blue-500/10 dark:bg-blue-500/15',
    border: 'hover:border-blue-500/40',
    featured: true,
  },
  {
    icon: BookOpen,
    title: '30-Day Learning Roadmap',
    description: 'Personalized learning plan with specific resources and weekly goals to close your exact skill gaps.',
    iconColor: 'text-emerald-600 dark:text-emerald-400',
    bg: 'bg-emerald-500/10 dark:bg-emerald-500/15',
    border: 'hover:border-emerald-500/40',
    featured: false,
  },
  {
    icon: FileText,
    title: 'Resume Analysis',
    description: 'Upload your CV and get AI-generated interview questions tailored directly to your unique background.',
    iconColor: 'text-pink-600 dark:text-pink-400',
    bg: 'bg-pink-500/10 dark:bg-pink-500/15',
    border: 'hover:border-pink-500/40',
    featured: false,
  },
  {
    icon: Trophy,
    title: 'Performance Analytics',
    description: 'Track progress over time with charts showing score trends and weak area identification across all sessions.',
    iconColor: 'text-amber-600 dark:text-amber-400',
    bg: 'bg-amber-500/10 dark:bg-amber-500/15',
    border: 'hover:border-amber-500/40',
    featured: false,
  },
  {
    icon: Zap,
    title: 'Multiple Interview Types',
    description: 'Practice technical, behavioral, system design, HR, or mixed formats — for any role, any level.',
    iconColor: 'text-cyan-600 dark:text-cyan-400',
    bg: 'bg-cyan-500/10 dark:bg-cyan-500/15',
    border: 'hover:border-cyan-500/40',
    featured: false,
  },
];

export function Features() {
  return (
    <section className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 -z-10 bg-gradient-to-b from-transparent via-muted/20 to-transparent" />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="text-sm font-semibold text-violet-600 dark:text-violet-400 tracking-wider uppercase">
            Everything You Need
          </span>
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mt-2 mb-4">
            Features that set you apart
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            A complete interview preparation platform with AI intelligence at every step of your journey.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.07 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className={`group relative p-6 rounded-2xl border border-border/50 bg-card/50 backdrop-blur-sm ${feature.border} hover:shadow-lg hover:shadow-black/5 transition-all duration-300`}
            >
              <div className={`w-12 h-12 rounded-xl ${feature.bg} flex items-center justify-center mb-5 group-hover:scale-110 transition-transform duration-300`}>
                <feature.icon className={`w-6 h-6 ${feature.iconColor}`} />
              </div>
              <h3 className="font-semibold text-base mb-2 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">
                {feature.title}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
