'use client';

import { motion } from 'framer-motion';
import {
  Brain, BarChart3, FileText, Trophy, Zap, Shield,
  Target, Clock, BookOpen
} from 'lucide-react';

const features = [
  {
    icon: Brain,
    title: 'AI-Powered Questions',
    description: 'Dynamic questions generated by Gemini AI, tailored to your specific role, experience level, and interview type.',
    color: 'from-violet-500 to-purple-600',
    bg: 'bg-violet-500/10',
  },
  {
    icon: BarChart3,
    title: 'Real-Time Scoring',
    description: 'Instant evaluation across 4 dimensions: technical knowledge, communication, relevance, and confidence.',
    color: 'from-blue-500 to-indigo-600',
    bg: 'bg-blue-500/10',
  },
  {
    icon: Target,
    title: 'Personalized Feedback',
    description: 'Detailed, constructive feedback on each answer to help you understand exactly where to improve.',
    color: 'from-emerald-500 to-teal-600',
    bg: 'bg-emerald-500/10',
  },
  {
    icon: BookOpen,
    title: '30-Day Roadmap',
    description: 'Personalized learning plan with specific resources and weekly goals based on your performance gaps.',
    color: 'from-orange-500 to-red-500',
    bg: 'bg-orange-500/10',
  },
  {
    icon: FileText,
    title: 'Resume Analysis',
    description: 'Upload your resume and get AI-generated interview questions tailored to your unique background.',
    color: 'from-pink-500 to-rose-600',
    bg: 'bg-pink-500/10',
  },
  {
    icon: Trophy,
    title: 'Performance Analytics',
    description: 'Track your progress over time with beautiful charts showing score trends and weak area identification.',
    color: 'from-yellow-500 to-amber-600',
    bg: 'bg-yellow-500/10',
  },
  {
    icon: Zap,
    title: 'Multiple Interview Types',
    description: 'Practice technical, behavioral, system design, HR, or mixed interviews for any role.',
    color: 'from-cyan-500 to-blue-600',
    bg: 'bg-cyan-500/10',
  },
  {
    icon: Shield,
    title: 'Export PDF Reports',
    description: 'Download comprehensive interview reports to share with mentors or track offline.',
    color: 'from-indigo-500 to-violet-600',
    bg: 'bg-indigo-500/10',
  },
  {
    icon: Clock,
    title: 'Interview History',
    description: 'Review past sessions, compare performance, and see your improvement trajectory at a glance.',
    color: 'from-teal-500 to-cyan-600',
    bg: 'bg-teal-500/10',
  },
];

export function Features() {
  return (
    <section className="py-24 relative overflow-hidden">
      <div className="absolute inset-0 -z-10 bg-gradient-to-b from-transparent via-muted/20 to-transparent" />
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <span className="text-sm font-semibold text-violet-600 dark:text-violet-400 tracking-wider uppercase">
            Everything You Need
          </span>
          <h2 className="text-4xl sm:text-5xl font-bold tracking-tight mt-2 mb-4">
            Features that set you apart
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            A complete interview preparation platform with AI intelligence at every step of your journey.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, index) => (
            <motion.div
              key={feature.title}
              initial={{ opacity: 0, y: 30 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.5, delay: index * 0.07 }}
              whileHover={{ y: -4, transition: { duration: 0.2 } }}
              className="group relative p-6 rounded-2xl border border-border/50 bg-card/50 backdrop-blur-sm hover:border-violet-500/30 hover:shadow-lg hover:shadow-violet-500/5 transition-all duration-300"
            >
              <div className={`w-12 h-12 rounded-xl ${feature.bg} flex items-center justify-center mb-4 group-hover:scale-110 transition-transform duration-300`}>
                <feature.icon className={`w-6 h-6 bg-gradient-to-r ${feature.color} bg-clip-text`} style={{ color: 'transparent', fill: 'none', stroke: `url(#grad-${index})` }} />
                <svg width="0" height="0" className="absolute">
                  <defs>
                    <linearGradient id={`grad-${index}`} x1="0%" y1="0%" x2="100%" y2="100%">
                      <stop offset="0%" className="stop-color-start" />
                      <stop offset="100%" className="stop-color-end" />
                    </linearGradient>
                  </defs>
                </svg>
                <feature.icon className={`w-6 h-6 bg-gradient-to-br ${feature.color} [-webkit-background-clip:text] [background-clip:text] text-transparent absolute`} />
              </div>
              <h3 className="font-semibold text-lg mb-2 group-hover:text-violet-600 dark:group-hover:text-violet-400 transition-colors">
                {feature.title}
              </h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
